version: "3.8"
services: 
  frontend: 
    build:
      context: ./frontend
    ports: 
      - "8080:8080"
    tty: true
    volumes: 
      - ./frontend/src:/app/src
      - /app/node_modules
  postgres:
    image: 'postgres:14.0'
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vueapi
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
  #  start mailhog
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - "1025:1025"  # smtp prot 
      - "8025:8025"  # web interface port 
    restart: always
